# Generated by Django 5.1.4 on 2025-01-13 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task11', '0002_auto_20250113_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='addrees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task11.address'),
        ),
    ]
