# Generated by Django 5.1.4 on 2025-01-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task11', '0003_alter_userprofile_addrees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='addrees',
            field=models.CharField(max_length=300),
        ),
    ]
