# Generated by Django 5.1.4 on 2025-01-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task11', '0004_alter_userprofile_addrees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='addrees',
        ),
    ]
