# Generated by Django 5.1.4 on 2025-01-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task11', '0005_remove_userprofile_addrees'),
    ]

    operations = [
    ]
