# Generated by Django 5.1.4 on 2025-01-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task10', '0001_initial'),
    ]

    operations = [
    ]
