# Generated by Django 5.1.4 on 2025-01-13 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task8', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialnumber',
            name='name',
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='serailnumber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task8.serialnumber'),
        ),
    ]
